### ISSUE TITLE
Writing to telnet host

### ISSUE THREAD

**Issue by coguy450** [sxyizhiren/telnetit#1]
Hi there, I love this node module. I'm having issues when invoking the write() function. It is sending the data across, but the server is not processing the request. I'm guessing a carriage return needs to be sent along with the text in the write function. Is there a way to add this in the data passed in? Or does a key function from the util-telnet.js file need to be invoked?

**Comment by sxyizhiren** [comment]
hi, @coguy450 
.write(xx) will sent whatever you pass in, xx could contain a RETURN or not. and will not append a RETURN by itsself.
but if the server must receive a RETURN('\r\n'), you may try like:

```
    var sentMsg = 'msg content ' + '\r\n';
    telnetcli.write(sentMsg ,function(){
      telnetcli.read(function(err,recv){
        recv=recv.join('');
        console.log('receive:',recv);

      });
    });
```

hope this can work .
